# Generated by Django 2.2.24 on 2022-03-16 16:03

import colorful.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0003_auto_20210823_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='bdtColor',
            field=colorful.fields.RGBColorField(default=django.utils.timezone.now, help_text='The RGB color values for Head text color.', verbose_name='body text color.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='bgColor',
            field=colorful.fields.RGBColorField(default=django.utils.timezone.now, help_text='The RGB color values for background page color.', verbose_name='Backgroud pages color.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='frameColor',
            field=colorful.fields.RGBColorField(default=django.utils.timezone.now, help_text='The RGB color values for frame background color.', verbose_name='frame background color.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='hlColor',
            field=colorful.fields.RGBColorField(default=django.utils.timezone.now, help_text='The RGB color values for Highlight color.', verbose_name='Highlight Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='htColor',
            field=colorful.fields.RGBColorField(default=django.utils.timezone.now, help_text='The RGB color values for help text color.', verbose_name='Help text color.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='logoLink',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, help_text='Logo link URL.', max_length=2000, unique=True, verbose_name='Logo Link URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='mmColor',
            field=colorful.fields.RGBColorField(default=django.utils.timezone.now, help_text='The RGB color values for first main menu bar color.', verbose_name='First Main menu Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='mtColor',
            field=colorful.fields.RGBColorField(default=django.utils.timezone.now, help_text='The RGB color values for main text color.', verbose_name='main text color.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='smmColor',
            field=colorful.fields.RGBColorField(default=django.utils.timezone.now, help_text='The RGB color values for second main menu color.', verbose_name='Second Main menu Color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='stylesheet',
            field=models.TextField(blank=True, help_text='The CSS stylesheet to change the appearance of the differentuser interface elements.', verbose_name='Stylesheet'),
        ),
        migrations.CreateModel(
            name='CurrentTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CurrentTheme', to='appearance.Theme', verbose_name='CurrentTheme')),
            ],
            options={
                'verbose_name': 'CurrentTheme',
                'verbose_name_plural': 'CurrentTheme',
            },
        ),
    ]
