# Generated by Django 2.2.24 on 2022-03-17 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0004_auto_20220316_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='fontLink',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, help_text='Font link URL.', max_length=2000, unique=True, verbose_name='font Link URL'),
            preserve_default=False,
        ),
    ]
